### ISSUE TITLE
出现下面问题如何解决，求教

### ISSUE THREAD

**Issue by weizbccccc** [SkyDependence/getFollowing#1]
Traceback (most recent call last):
  File "D:\Favorites\getIwara\getIwaraUsername.py", line 187, in <module>
    scrape_iwara_following(USERNAME, PASSWORD)
  File "D:\Favorites\getIwara\getIwaraUsername.py", line 126, in scrape_iwara_following
    raise e
  File "D:\Favorites\getIwara\getIwaraUsername.py", line 122, in scrape_iwara_following
    page.wait_for_selector('div.text.text--truncate.text--muted.text--small', timeout=10000)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 8006, in wait_for_selector
    self._sync(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_page.py", line 397, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 10000ms exceeded.
Call log:
waiting for locator("div.text.text--truncate.text--muted.text--small") to be visible

**Comment by SkyDependence** [comment]
有完整的日志吗？你前面的日志中有出现“登录成功！”吗？请给我更多的信息

**Comment by SkyDependence** [comment]
我成功复现了你的错误，你应该是没有挂代理，导致连接不上iwara，你试试用浏览器上iwara看看能不能访问。不能访问的话要挂代理

> Traceback (most recent call last): File "D:\Favorites\getIwara\getIwaraUsername.py", line 187, in scrape_iwara_following(USERNAME, PASSWORD) File "D:\Favorites\getIwara\getIwaraUsername.py", line 126, in scrape_iwara_following raise e File "D:\Favorites\getIwara\getIwaraUsername.py", line 122, in scrape_iwara_following page.wait_for_selector('div.text.text--truncate.text--muted.text--small', timeout=10000) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api_generated.py", line 8006, in wait_for_selector self._sync( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright_impl_sync_base.py", line 115, in _sync return task.result() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright_impl_page.py", line 397, in wait_for_selector return await self._main_frame.wait_for_selector(**locals_to_params(locals())) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright_impl_frame.py", line 323, in wait_for_selector await self._channel.send("waitForSelector", locals_to_params(locals())) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright_impl_connection.py", line 59, in send return await self._connection.wrap_api_call( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright_impl_connection.py", line 514, in wrap_api_call raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 10000ms exceeded. Call log: waiting for locator("div.text.text--truncate.text--muted.text--small") to be visible
